/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Active': '激活',
    'Age': '年龄',
    'Beggar': '乞丐',
    'Beggar lvl': '乞丐等级',
    'House': '房子',
    'Holy knight': '圣骑士',
    'Import': '导入',
    'Import/export save': '导入/导出存档',
    'Farmer': '农民',
    'Export': '导出',
    'Evil': '邪恶',
    'Evil control': '邪恶控制',
    'Expense/day': '费用/天',
    'years': '年',
    'Xp/day': '经验/天',
    'xp multipliers': '经验倍数',
    'Xp left': '经验剩余',
    'Level': '等级',
    'Library': '图书馆',
    'Mage': '法师',
    'Lifespan': '寿命',
    'Magic': '魔法',
    'Mana control': '法力控制',
    'Master wizard': '精灵法师',
    'Max level': '最高级',
    'Miner': '矿工',
    'Misc': '杂项',
    'Jobs': '工作',
    'Skills': '技能',
    'Shop': '商店',
    'Pause': '暂停',
    'Personal squire': '私人护卫',
    'Required: ': '要求: ',
    'Reset': '重置',
    'Sapphire charm': '蓝宝石护符',
    'Settings': '设置',
    'Skip': '跳过',
    'Squire': '护卫',
    'Student': '学生',
    'Steel longsword': '钢长剑',
    'Study desk': '书桌',
    'Task': '任务',
    'Toggle': '切换',
    'Touch the eye': '注视',
    'Wizard': '巫师',
    'Wooden hut': '木屋',
    'Properties': '属性',
    'Progress Knight': '骑士进度条',
    'Small palace': '小宫殿',
    'Strength': '力量',
    'Tent': '帐篷',
    'The Arcane Association': '奥术协会',
    'Veteran footman': '资深仆人',
    'Veteran knight': '资深骑士',
    'Toggle light/dark mode': '切换亮/暗模式',
    'Time warping': '时间扭曲',
    'Amulet': '护身符',
    'Age has caught up to you': '年龄已经赶上了你',
    'Apprentice mage': '学徒法师',
    'Auto-learn': '自动学习',
    'Auto-promote': '自动提升',
    'Book': '书',
    'Chairman': '会长',
    'Combat': '战斗',
    'Cottage': '茅屋',
    'Current job': '当前工作',
    'Current skill': '当前技能',
    'Dark magic': '黑暗魔法',
    'Super immortality': '超级永生',
    'Net/day': '净/天',
    'Muscle memory': '肌肉记忆',
    'Military': '军事',
    'Merchant': '商人',
    'Meditation': '冥想',
    'Large house': '大房子',
    'Knight': '骑士',
    'Join the discord community!': '加入discord社区！',
    'Intimidation': '威胁',
    'Immortality': '永生',
    'Income/day': '收入/天',
    'Homeless': '无家可归',
    'Hard reset game': '硬重置',
    'Grand palace': '大宫殿',
    'Fundamentals': '基本原理',
    'Elite knight': '精英骑士',
    'Effect': '效果',
    'Dumbbells': '哑铃',
    'Day': '天',
    'Dark influence': '邪恶势力',
    'Demon training': '魔鬼训练',
    'Disable warp': '禁用扭曲',
    'Common work': '常规工作',
    'Butler': '男仆',
    'Blood meditation': '血之冥想',
    'Concentration': '专注',
    'Bargaining': '讨价还价',
    'Battle tactics': '战斗战术',
    'Blacksmith': '铁匠',
    'Affects game speed': '影响游戏速度',
    'Affects dark magic xp gain': '影响黑魔法经验收益',
    'Affects all xp gain': '影响所有经验收益',
    'Concentration lvl': '专注等级',
    'evil': '邪恶',
    'Fisherman': '渔夫',
    'Footman': '男仆',
    'Happiness': '幸福',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'for your jobs and skills equivalent to': '对你的工作和技能相当',
    'Fill your mind with peace and tranquility to tap into greater happiness from within.': '让你的头脑充满和平与安宁，从内心发掘更大的幸福。',
    'Feared worldwide, obliterate entire nations in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.': '让全世界都感到恐惧，一眨眼的功夫就把整个国家都毁灭了。大约每个世纪，只有一位神圣骑士配得上这样一个受人尊敬的头衔。',
    'A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.': '一座完全由金银构成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。',
    'A fine blade used to slay enemies even quicker in combat and therefore gain more experience.': '在战斗中可以更快地杀死敌人，从而获得更多经验。',
    'A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.': '仅仅是人的身体就太软弱无力，无法抵挡邪恶。用禁止的方法训练，慢慢变成一个能够快速吸收知识的恶魔。',
    'A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.': '一个写下你所有想法和发现的地方，让你学得更快。',
    'A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.': '一张由两根软弱的木棒托着的破布。生活条件很糟糕，但至少你有个栖身之所。',
    'A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.': '一个非常丰富和精心建造的结构，镶有精细的金属，如银。维持奢华的生活方式需要极高的费用。',
    'Assists you in completing day to day activities, giving you more time to be productive at work.': '帮助你完成每天的活动，给你更多的时间在工作中更有效率。',
    'Bend space and time through forbidden techniques, resulting in a faster gamespeed.': '通过禁止的技术扭曲空间和时间，导致更快的游戏速度。',
    'Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that a master wizard has enough destructive power to wipe an empire off the map.': '拥有无与伦比的天赋，可以随心所欲地施展难以置信的魔术。据说巫师大师拥有足够的破坏力，足以将一个帝国从地图上抹去。',
    'More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.': '比普通男仆更有经验，更有用，在战斗中用你的力量消灭敌人。(工资没那么低。)',
    'Study the tricks of the trade and persuasive skills to lower any type of expense.': '学习交易技巧和说服技巧来降低任何类型的费用。',
    'Tame the raging and growing evil within you, improving evil gain in-between rebirths.': '驯服你内心的愤怒和增长的邪恶，在转世之间提高邪恶增益。',
    'This means you will learn everything again much more quickly than you did in your previous life.': '这意味着你学习每一件事的速度要比你以前更快。',
    'Through harnessing ancient, forbidden techniques, lengthen your lifespan drastically beyond comprehension.': '通过利用古老的、被禁止的技术，将你的寿命大大延长到无法理解的程度。',
    'Through the means of dark magic, multiply the raw matter of the coins you receive from your job.': '通过黑魔法，将您从工作中获得的硬币的原始物质相乘。',
    'Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.': '从一个城镇到另一个城镇，以物易物。这份工作报酬不错，而且不需要太多的体力劳动。',
    'Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.': '通过施放中间法术和指导其他学徒来扭转战斗的趋势。这份工作的报酬非常高。',
    'Under the supervision of a mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.': '在法师的指导下，在战斗中对敌人施展基本法术。将提供相当数量的工资以支付生活费用。',
    'Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.': '使用先进的法术来蹂躏和摧毁整个军团的敌人士兵。只有一小部分的法师配得上这个角色，并能得到高得离谱的报酬。',
    'Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.': '利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队里的大多数男仆都不可能得到这样一份报酬优厚的工作。',
    'Your age has met your lifespan, use the amulet to rebirth before you pass away': '你的年龄已经达到了你的寿命，用护身符在你死前重生',
    'Improve your learning speed through practising intense concentration activities.': '通过练习集中注意力的活动来提高你的学习速度。',
    'A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.': '一个专门的区域，提供了许多精致的文具和装备设计，以促进您的研究进展。',
    'A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.': '用石头、砖和坚固的木材建造的建筑，里面有几个房间。虽然很贵，但这是一个舒适的住所。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Strength level ": "力量等级 ",
    "Farmer level ": "农民等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^x([\d\.]+) Happiness$/, 'x$1 幸福值'],
    [/^Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n(.+)A mouth emerges from its surface and begins to cackle, and proceeds to say: "So you've made it this far... Are you ready to embrace evil?"$/, '你的直觉是对的。当你到达200岁的时候，你会听到护身符发出不祥的嗡嗡声。一张嘴从它的表面露出来，咯咯地笑着说:“你已经走到这一步了……你准备好迎接邪恶了吗?”'],
    [/^You stumble across a strange looking amulet on your 25th birthday. It does not look like\n(.+)it has any worth on the market given that it's made from cheap-looking copper. However, you\n(.+)feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.$/, '你在25岁生日时偶然发现了一个奇怪的护身符。它看起来不像在市场上有任何价值，因为它是由看起来很便宜的铜制成的。然而，你有一种奇怪的冲动想要保存这个护身符，所以你把它放进口袋里妥善保管。'],
    [/^Concentration level (.+)\/(.+), Meditation level (.+)\/$/, '专注等级 $1\/$2，冥想等级 $3\/'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);